### ISSUE TITLE
sometimes got POPO__CHUNK_LOCKING_ERROR

### ISSUE THREAD

**Issue by qclzdh** [eclipse-iceoryx/iceoryx#999] opened 2021-12-30 10:54 UTC
## Required information

**Operating system:**
E.g. Ubuntu 18.04 LTS

**Compiler version:**
E.g. GCC 7.4.0

**Observed result or behaviour:**
got this error during publishing data:
**_iceoryx/iceoryx_hoofs/source/posix_wrapper/mutex.cpp:67 { bool iox::posix::mutex::lock() -> pthread_mutex_lock }  :::  [ 0 ]  Success
ICEORYX error! POPO__CHUNK_LOCKING_ERROR
iceoryx_hoofs/source/error_handling/error_handling.cpp:57: static void iox::ErrorHandler::ReactOnErrorLevel(iox::ErrorLevel, const char*): Assertion `false' failed._** 

**Expected result or behaviour:**
What do you expect to happen?
No error happend

**Conditions where it occurred / Performed steps:**
Describe how one can reproduce the bug.
It's very difficult to reproduce this error, but i already see this error several times.

Could you give some hints, why this happened?

**Comment by elfenpiff** [comment] 2022-01-01 20:39
@qclzdh I looked at the code and found a bug in our mutex implementation which causes the mutex to print always `[ 0 ] Success` as error message.
Could you please check out my pull request #1000 , try your code again with the mutex fix and provide me the updated error message. Then I can continue my bug hunt.

**Comment by qclzdh** [comment] 2022-01-02 13:43
Thanks, @elfenpiff , i will run with the patch again, and update the result to you.

**Comment by qclzdh** [comment] 2022-01-02 14:52
@elfenpiff , with the new path, i got this error: 
**_iceoryx/iceoryx_hoofs/source/posix_wrapper/mutex.cpp:67 { bool iox::posix::mutex::lock() -> pthread_mutex_lock }  :::  [ 22 ]  Invalid argument
terminate called without an active exception
Aborted_**

**Comment by elBoberido** [comment] 2022-01-03 11:29
@qclzdh do you have a few more information on how to reproduce this, e.g. are there multiple publishers or multiple subscribers? Was an application stopped or died before this happened?

**Comment by qclzdh** [comment] 2022-01-05 01:42
i compile iox with one-to-many-only, and there is several subscribers in different process, i re-checked the log, one warning log "[Warning]: Application xxxxx_336 not responding (last response 1563 milliseconds ago) --> removing it" appeared before this locking error, is this related?

**Comment by elBoberido** [comment] 2022-01-05 10:27
@qclzdh yes, this is related. Can you share more information like the `PublisherOptions` and `SubscriberOptions`? How fast is the publisher sending data?

As far as I know `one-to-many-only` is not as much tested as `many-to-many`. Could you check if the error also occurs when you don't use `on-to-many-only`? This would help to narrow the error cause down.

**Comment by qclzdh** [comment] 2022-01-05 12:21
@elBoberido  , here is options:
_PublisherOptions.historyCapacity: 0U
PublisherOptions.nodeName: ""
PublisherOptions.offerOnCreate: true
PublisherOptions.SubscriberTooSlowPolicy: iox::popo::SubscriberTooSlowPolicy::DISCARD_OLDEST_DATA

SubscriberOptions.queueCapacity: 16U
SubscriberOptions.historyRequest: 0U
SubscriberOptions.nodeName: ""
SubscriberOptions.subscribeOnCreate: true
SubscriberOptions.queueFullPolicy:iox::popo::QueueFullPolicy::DISCARD_OLDEST_DATA_

How fast is the publisher sending data?  --->> very fast, i test it with while(1), and has no delay/sleep.

It seems it takes few days on ubuntu, but it takes hours on arm64-qemu, i just got more log, the log format means,
(353/350), 353-->tid, 350-->pid
(xxx/350),  this log is from one process which has some subscribers and publishers.
(xxx/245):  this log is from iox-roud.
from the log, it looks like, timedWait didn't wakeup timely, no keep alive MSG to roudi within 1.5s, so roudi killed this process.


[2022-01-05 11:51:49.510065] W/iceoryx(353/350): 2022-01-05 11:51:49.509 [Warning]: sending keep alive
[2022-01-05 11:51:49.512830] W/iceoryx(353/350): 2022-01-05 11:51:49.512 [Warning]: sendKeepAliveAndHandleShutdownPreparation
[2022-01-05 11:51:49.849028] W/iceoryx(353/350): keep live thread wake from timedWait
[2022-01-05 11:51:49.851879] W/iceoryx(353/350): keep live thread call m_callable
[2022-01-05 11:51:49.854752] W/iceoryx(353/350): 2022-01-05 11:51:49.854 [Warning]: sending keep alive
[2022-01-05 11:51:49.868315] W/iceoryx(353/350): 2022-01-05 11:51:49.868 [Warning]: sendKeepAliveAndHandleShutdownPreparation
[2022-01-05 11:51:50.179458] W/iceoryx(353/350): keep live thread wake from timedWait
[2022-01-05 11:51:50.179585] W/iceoryx(353/350): keep live thread call m_callable
[2022-01-05 11:51:50.179863] W/iceoryx(353/350): 2022-01-05 11:51:50.179 [Warning]: sending keep alive
[2022-01-05 11:51:50.193033] W/iceoryx(353/350): 2022-01-05 11:51:50.192 [Warning]: sendKeepAliveAndHandleShutdownPreparation
[2022-01-05 11:51:50.378504] W/iceoryx(307/245): keep live thread wake from timedWait
[2022-01-05 11:51:50.378629] W/iceoryx(307/245): keep live thread call m_callable
[2022-01-05 11:51:50.378988] W/iceoryx(308/245): keep live thread wake from timedWait
[2022-01-05 11:51:50.379088] W/iceoryx(308/245): keep live thread call m_callable
[2022-01-05 11:51:50.380017] W/iceoryx(309/245): keep live thread wake from timedWait
[2022-01-05 11:51:50.380301] W/iceoryx(309/245): keep live thread call m_callable
[2022-01-05 11:51:50.504497] W/iceoryx(353/350): keep live thread wake from timedWait
[2022-01-05 11:51:50.504624] W/iceoryx(353/350): keep live thread call m_callable
[2022-01-05 11:51:50.504952] W/iceoryx(353/350): 2022-01-05 11:51:50.504 [Warning]: sending keep alive
[2022-01-05 11:51:50.509818] W/iceoryx(353/350): 2022-01-05 11:51:50.509 [Warning]: sendKeepAliveAndHandleShutdownPreparation
[2022-01-05 11:51:50.810246] W/iceoryx(353/350): keep live thread wake from timedWait
[2022-01-05 11:51:50.810390] W/iceoryx(353/350): keep live thread call m_callable
[2022-01-05 11:51:50.810762] W/iceoryx(353/350): 2022-01-05 11:51:50.810 [Warning]: sending keep alive
[2022-01-05 11:51:50.812424] W/iceoryx(353/350): 2022-01-05 11:51:50.812 [Warning]: sendKeepAliveAndHandleShutdownPreparation
[2022-01-05 11:51:51.379811] W/iceoryx(307/245): keep live thread wake from timedWait
[2022-01-05 11:51:51.379981] W/iceoryx(307/245): keep live thread call m_callable
[2022-01-05 11:51:51.380336] W/iceoryx(308/245): keep live thread wake from timedWait
[2022-01-05 11:51:51.380437] W/iceoryx(308/245): keep live thread call m_callable
[2022-01-05 11:51:51.380767] W/iceoryx(309/245): keep live thread wake from timedWait
[2022-01-05 11:51:51.380869] W/iceoryx(309/245): keep live thread call m_callable
[2022-01-05 11:51:52.380467] W/iceoryx(307/245): keep live thread wake from timedWait
[2022-01-05 11:51:52.380620] W/iceoryx(307/245): keep live thread call m_callable
[2022-01-05 11:51:52.381181] W/iceoryx(308/245): keep live thread wake from timedWait
[2022-01-05 11:51:52.381294] W/iceoryx(308/245): keep live thread call m_callable
[2022-01-05 11:51:52.381468] W/iceoryx(309/245): keep live thread wake from timedWait
[2022-01-05 11:51:52.381562] W/iceoryx(309/245): keep live thread call m_callable
[2022-01-05 11:51:52.403250] W/iceoryx(310/245): 2022-01-05 11:51:52.400 [Warning]: Application ARACOM_350 not responding (last response 1589 milliseconds ago) --> removing it
[2022-01-05 11:51:52.678946] W/iceoryx(351/350): 2022-01-05 11:51:52.678 [Warning]: ICEORYX error! POPO__CHUNK_SENDER_INVALID_CHUNK_TO_SEND_FROM_USER
[2022-01-05 11:51:53.381169] W/iceoryx(307/245): keep live thread wake from timedWait
[2022-01-05 11:51:53.381303] W/iceoryx(307/245): keep live thread call m_callable
[2022-01-05 11:51:53.382108] W/iceoryx(308/245): keep live thread wake from timedWait
[2022-01-05 11:51:53.382210] W/iceoryx(308/245): keep live thread call m_callable
[2022-01-05 11:51:53.382426] W/iceoryx(309/245): keep live thread wake from timedWait
[2022-01-05 11:51:53.382519] W/iceoryx(309/245): keep live thread call m_callable
[2022-01-05 11:51:53.502339] W/iceoryx(355/350): 2022-01-05 11:51:53.502 [Warning]: ICEORYX error! POPO__CHUNK_RECEIVER_INVALID_CHUNK_TO_RELEASE_FROM_USER
[2022-01-05 11:51:53.545493] W/iceoryx(353/350): keep live thread wake from timedWait
[2022-01-05 11:51:53.556738] W/iceoryx(353/350): keep live thread call m_callable
[2022-01-05 11:51:53.560927] W/iceoryx(353/350): 2022-01-05 11:51:53.560 [Warning]: sending keep alive
[2022-01-05 11:51:53.562095] W/iceoryx(312/245): 2022-01-05 11:51:53.561 [Warning]: Received Keepalive from unknown process ARACOM_350
[2022-01-05 11:51:53.567152] W/iceoryx(353/350): 2022-01-05 11:51:53.566 [Warning]: sendKeepAliveAndHandleShutdownPreparation
[2022-01-05 11:51:53.508718] W/iceoryx(351/350): /home/qianchunlei/project/fengshen/external/iceoryx/iceoryx-0eac2ac/iceoryx_hoofs/source/posix_wrapper/mutex.cpp:67 { bool iox::posix::mutex::lock() -> pthread_mutex_lock }  :::  [ 0 ]  Success
[2022-01-05 11:51:53.567854] E/iceoryx(351/350): 2022-01-05 11:51:53.567 [ Error ]: ICEORYX error! POPO__CHUNK_LOCKING_ERROR
[2022-01-05 11:51:54.382301] W/iceoryx(307/245): keep live thread wake from timedWait
[2022-01-05 11:51:54.382471] W/iceoryx(307/245): keep live thread call m_callable
[2022-01-05 11:51:54.383022] W/iceoryx(308/245): keep live thread wake from timedWait
[2022-01-05 11:51:54.383132] W/iceoryx(308/245): keep live thread call m_callable
[2022-01-05 11:51:54.383298] W/iceoryx(309/245): keep live thread wake from timedWait

**Comment by elBoberido** [comment] 2022-01-06 14:44
@qclzdh with your question in mind related to thread safety of publisher and subscriber and the errors with the same pid but different tid, is the publisher guarded by a mutex?

**Comment by budrus** [comment] 2022-01-20 17:01
@qclzdh Have you tried the proposal from @elBoberido. Publishers and Subscribers are not thread safe on their API, ao you would have to protect with a mutex or our smart_lock

**Comment by qclzdh** [comment] 2022-01-21 01:51
@budrus Finally, i understand why this happened in my side.
1. this locking error "pthread_mutex_lock } ::: [ 22 ] Invalid argument" was caused due to roudi kill that process, since roudi didn't received keepalive msg within 1.5s.
2. There are some socket sending in the test application, at the worst case, that sending operation will block about ~2s, this block will affect all the thread on the same cpu, so when the keepalive thread is on the same cpu with that blocking operation, there are some chance that keepalive message won't be sent to roudi. This also can explatin, why it is difficult to reproduce on ubuntu, since it has 8 processors, but we only use one processor in aarch64-qemu.

**Comment by qclzdh** [comment] 2022-01-21 02:00
@budrus  Yes, we used mutex for those APIs.

**Comment by elBoberido** [comment] 2022-01-21 09:47
@qclzdh there is an option to run RouDi without monitoring `-m off` but then you (potentionally) loose the cleanup of terminated processes. I'm not quite sure if the cleanup kicks in when the application tries to register again at RouDi

**Comment by qclzdh** [comment] 2022-01-21 14:32
@elBoberido thanks, i noticed this, and disable the monitor mode.

**Comment by budrus** [comment] 2022-02-03 16:55
@qclzdh As far as I understood you know know what the problem was. Then I would close this issue. Feel free to reopen if you still have a problem

**Closed by budrus** 2022-02-03 16:55 UTC
Labels: bug
