### ISSUE TITLE
 program crashes 

### ISSUE THREAD

**Issue by owny990312** [eclipse-iceoryx/iceoryx#2388] opened 2024-12-12 03:13 UTC
![image](https://github.com/user-attachments/assets/f231e695-bffc-4755-b073-35154c1044c4)

The program crashes at the location indicated in the image below when performing breakpoint debugging or deliberately throwing exceptions

**Comment by owny990312** [comment] 2024-12-12 03:29
> ![image](https://private-user-images.githubusercontent.com/89577994/394994153-f231e695-bffc-4755-b073-35154c1044c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzQ0NDAsIm5iZiI6MTczMzk3NDE0MCwicGF0aCI6Ii84OTU3Nzk5NC8zOTQ5OTQxNTMtZjIzMWU2OTUtYmZmYy00NzU1LWIwNzMtMzUxNTRjMTA0NGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAzMjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YWIzZjFkYzYzZDVmMWYyZTQ5NWY3ZDY3NmI1NTZiMGY2ZjEyNjU4OGFkNTRkYzNlMGI2YTk1NzdkYzg3MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1_u5_oX8_lKX2vFFVPXvQWmuO1MRgiXeWW_BTs2BnS4)
> 
> The program crashes at the location indicated in the image below when performing breakpoint debugging or deliberately throwing exceptions程序在下方图片中标示的位置在进行断点调试或故意抛出异常时崩溃

I just set a breakpoint

**Comment by elfenpiff** [comment] 2024-12-12 06:41
@owny990312 

>  or deliberately throwing exceptions

iceoryx does not support exceptions since every method or function is marked with `noexcept`.

> The program crashes at the location indicated in the image below when performing breakpoint debugging

The location where the program crashes is the error handler that is called when iceoryx runs into a failure situation. In that case iceoryx shall terminate, otherwise iceoryx would continue with undefined behavior or the system would be corrupted.

Could you give us some more context information? The best thing would be a minimalistic iceoryx example so that we can reproduce the issue and fix it on our side. If this is not possible than a minimalistic code snippet that shows roughly how the mis-behavior/bug can be triggered.

**Comment by owny990312** [comment] 2024-12-12 08:05
> @owny990312
> 
> > or deliberately throwing exceptions或故意抛出异常
> 
> iceoryx does not support exceptions since every method or function is marked with `noexcept`.iceoryx 不支持异常，因为每个方法或函数都标记为 `noexcept`。
> 
> > The program crashes at the location indicated in the image below when performing breakpoint debugging程序在下方图片中标示的位置在进行断点调试时崩溃
> 
> The location where the program crashes is the error handler that is called when iceoryx runs into a failure situation. In that case iceoryx shall terminate, otherwise iceoryx would continue with undefined behavior or the system would be corrupted.程序崩溃的位置是 iceoryx 遇到失败情况时调用的错误处理程序。在这种情况下 iceoryx 应当终止，否则 iceoryx 会继续以未定义的行为运行或系统会被破坏。
> 
> Could you give us some more context information? The best thing would be a minimalistic iceoryx example so that we can reproduce the issue and fix it on our side. If this is not possible than a minimalistic code snippet that shows roughly how the mis-behavior/bug can be triggered.如果这不可能的话，那么提供一个极简的代码片段，显示如何触发该异常/bug。

I just set a breakpoint, then the program broken down .

**Comment by elfenpiff** [comment] 2024-12-12 13:35
@owny990312 could you try to start roudi with disabled monitoring and tell me if the problem still persists?

So: `./build/iox-roudi -m off`

**Comment by owny990312** [comment] 2024-12-13 01:36
> ./build/iox-roudi -m off
it works！ Could you explain the underlying principles, Thanks

**Comment by elfenpiff** [comment] 2024-12-13 08:15
@owny990312 My guess was that you are running into a monitoring issue. When debugging and interrupting a process, the regular heartbeat is no longer sent, and our central broker, roudi, assumes then that the application is dead or some other timing contract is not satisfied, which then can cause your error.

**Comment by owny990312** [comment] 2024-12-16 01:19
> @owny990312 My guess was that you are running into a monitoring issue.我的猜测是你们遇到了监控问题。 When debugging and interrupting a process, the regular heartbeat is no longer sent, and our central broker, roudi, assumes then that the application is dead or some other timing contract is not satisfied, which then can cause your error.在调试和中断一个进程时，常规的心跳不再发送，然后我们的中央代理 roudi 会假设该应用程序已死亡或某些其他时间合同未得到满足，这可能会导致你的错误。

Thanks for your reply

**Comment by elfenpiff** [comment] 2024-12-16 13:08
@owny990312 Since your question was answered I am closing the issue.

Please feel free to reopen it, when another issue arises in the same context.

**Closed by elfenpiff** 2024-12-16 13:08 UTC
