### ISSUE TITLE
system time change cause POPO__CHUNK_LOCKING_ERROR

### ISSUE THREAD

**Issue by JasonWang-Slamtec** [eclipse-iceoryx/iceoryx#2381] opened 2024-12-04 03:43 UTC
## Required information

**Operating system:**
E.g. Ubuntu 20.04 LTS

**Compiler version:**
E.g. GCC 9

**Eclipse iceoryx version:**
E.g. `v2.0.3`

**Observed result or behaviour:**
process A  is publisher, process B is subscriber
when system time changed,  A output following log and crashed:
../iceoryx-2.0.3/iceoryx_hoofs/source/posix_wrapper/mutex.cpp:68 { bool iox::posix::mutex::lock() -> pthread_mutex_lock }  :::  [ 22 ]  Invalid argument
2024-12-04 11:27:16.335 [ Error ]: ICEORYX error! POPO__CHUNK_LOCKING_ERROR
after A rebooted, B can no longer receive data, while roudi is printing following logs:
2024-12-04 11:40:45.528 [Warning]: Received Keepalive from unknown process B
Communication returned to normal after B was restarted, 

i use following command to change time:
date 120411312024.15

**Comment by elBoberido** [comment] 2024-12-04 10:56
This is a duplicate of #2193.

Unfortunately, this bug is not easy to fix. You can have a look at that issue for workarounds.

We have an idea how to properly fix it, but it's nothing which is done in an afternoon and takes quite some time.

Most of the iceoryx developers shifted their focus towards iceoryx2, where this problem does not occur. Is iceoryx2 also an option for you?

Alternatively, the root README.md has a link to commercial support for iceoryx in case the workarounds do not work for you and you cannot switch to iceoryx2.

To keep the technical discussion for this bug at a central place (#2193), I'll close this issue.

**Closed by elBoberido** 2024-12-04 10:56 UTC
