### ISSUE TITLE
It seems lost data with high frequence

### ISSUE THREAD

**Issue by jhx2002** [eclipse-iceoryx/iceoryx#668] opened 2021-04-02 09:44 UTC
Test version 0.99.0
I have set the subscriber.queueCapacity > total send count
Some messages  are lost when publish every 10ms.

**Comment by budrus** [comment] 2021-04-02 19:11
@jhx2002 We need more info. 
1. There is a compile time max queue capacity of 256. What value have you set? If you set a value larger than 256 it will be limited and a warning is printed. The max capacity can be configured, this is because we have static memory and have to do a compromise between footprint and flexibility 
2. Can you check if the subscriber detected a queue overflow? The subscriber has a `hasMissedData()` which return true if you had a queue overflow between two calls of this method. If it returns true you are sending faster than the subscriber is consuming. Also in future the default contract is that the subscriber has a queue capacity and it is guaranteed that you get up to capacity latest samples. But if there are more we drop the oldest
3. Do you first start the subscriber and then the publisher? If you do not use history or the history capacity is not large enough, you will loose data when the subscriber is started later and the publisher already sent data
4. Do you use a waitset or listener or do you poll on the subscriber side?
5. the 0.99.0 version is our RC1 for the 1.0.0 Almond release. The option to block the publisher is not yet available. There is already a PR but it didn't made it in time [https://github.com/eclipse-iceoryx/iceoryx/pull/663](https://github.com/eclipse-iceoryx/iceoryx/pull/663) It should be on master in a few days and will be in the final release. Here you would have to enable this feature to ensure you are not loosing data if the subscriber is not fast enough and the queue overflows

**Comment by budrus** [comment] 2021-04-02 20:19
@jhx2002 just made some tests
1. I took the icedelivery examples for untyped publisher and subscriber
2. If the sleep on subscriber side is larger than on publisher side I loose a lot sample. That's what I expect 
3. If if have the same 1ms sleep on both sides with queue capacity 10 I loose from time to time a sample. I check a counter and `hasMissedData()`. Every time when I loose a sample both printfs are coming, so I loose them because of a queue overflow. When both have the same high frequency, I guess because of OS scheduling a queue size of 10 could already be a problem
4. I introduced a waitset on subcriber side and further increased the frequency on publisher side. I'm sending ever 100 µs and let it run for 10 minutes. No sample was lost. But I guess this is a frequency range where we could also have overflows with small queue sizes on a non real-time system

**Comment by jhx2002** [comment] 2021-04-03 02:47
what is the difference of waitset and queue of subscriber?

**Comment by jhx2002** [comment] 2021-04-03 07:49
I test with multiple publisher and subscriber. Can you test with this situation?

**Comment by budrus** [comment] 2021-04-03 15:49
@jhx2002 see [here](https://github.com/eclipse-iceoryx/iceoryx/issues/656#issuecomment-810037293) what @elfenpiff already answered for what happens if the queue is full. 
The waitset (and the listener) are the alternatives to polling. I.e. your waitset gets woken up, when a new sample is pushed to the queue. This ensures that your subscriber starts consuming as fast as possible. 

The simplest waitset example would be (I recommend evaluating the return values though)
```
#include "iceoryx_posh/popo/subscriber.hpp"
#include "iceoryx_posh/runtime/posh_runtime.hpp"
#include "iceoryx_posh/popo/wait_set.hpp"

#include <iostream>

int main()
{
    // initialize runtime
    iox::runtime::PoshRuntime::initRuntime("my_app");

    // create subscriber
    iox::popo::Subscriber<RadarObject> subscriber({"Radar", "FrontLeft", "Object"});
    
    // create waitset
    iox::popo::WaitSet<1> waitset;
    
    // attach subscriber to waitset
    waitset.attachState(subscriber, iox::popo::SubscriberState::HAS_DATA);

    // this is 4 ever
    while (true)
    {
        // wait for samples to arrive
        waitset.wait();

        // consume a sample
        subscriber.take()
            .and_then([](auto& sample) { std::cout << " got value: " << sample->x << std::endl; });
    }

    return (EXIT_SUCCESS);
}
```
You can also give the blocking publisher functionality a try now. It is already on the [release branch](https://github.com/eclipse-iceoryx/iceoryx/tree/release_1.0) 
All you have to do is enable the option for publisher and subscriber
```
    iox::popo::SubscriberOptions subscriberOptions;
    subscriberOptions.receiverQueueFullPolicy = iox::popo::QueueFullPolicy::BLOCK_PUBLISHER;
    iox::popo::UntypedSubscriber subscriber({"Radar", "FrontLeft", "Object"}, subscriberOptions);

    iox::popo::PublisherOptions publisherOptions; 
    publisherOptions.deliveryQueueFullPolicy = iox::popo::SubscriberTooSlowPolicy::WAIT_FOR_SUBSCRIBER;
    iox::popo::UntypedPublisher publisher({"Radar", "FrontLeft", "Object"}, publisherOptions);
```

**Comment by budrus** [comment] 2021-04-03 15:53
@elBoberido @FerdinandSpitzschnueffler @mossmaurice . I feel we need a waitset example almost as simple as the one above

**Comment by elBoberido** [comment] 2021-04-03 16:08
> @elBoberido @FerdinandSpitzschnueffler @mossmaurice . I feel we need a waitset example almost as simple as the one above

@budrus I agree with one notable exception. This must be
```
constexpr bool THIS_IS_4_EVER {true};
while (THIS_IS_4_EVER)
```
🤓

**Comment by MatthiasKillat** [comment] 2021-04-07 12:21
Note that the using the waitset with infrequent data and a ``while(true)`` loop is a bad idea. How could we ever leave this loop? This unfortunately requires attaching an additional trigger to modify the termination condition. But then it is not that simple to use anymore, we need to look at the reason we woke up, i.e. the result of the `wake()` call. 

Currently this result is ignored, but it is shown in the ice_waitset_individual.cpp example how to use the wake up result. Unfortunately this makes the code less elegant. This could be fixed by providing a specific wake-up function for the waitset, but then the invariant that we never wake up with an empty result vector would not hold anymore. 

The API will not be changed in 1.0, but this is something we should consider when improving the waitset.

**Comment by elBoberido** [comment] 2021-04-19 11:38
@jhx2002 could you provide more information like requested? With __Almond__ there is the option to let a slow subscriber block a publisher in order to not lose any sample.

If we don't get any response, we assume the problem is solved and close the issue in two weeks.

**Comment by elBoberido** [comment] 2021-05-03 11:54
@jhx2002 I assume the problem is solved with the __Almond__ release and close the issue. Feel free to reopen it again if it's not the case.

**Closed by elBoberido** 2021-05-03 11:54 UTC
