### ISSUE TITLE
app crash OSH__SHM_APP_MAPP_ERR

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx#1763] opened 2022-10-27 03:23 UTC
## Required information

**Operating system:**
E.g. Ubuntu 18.04 LTS

**Compiler version:**
E.g. GCC 7.4.0

**Observed result or behaviour:**
A clear and precise description of the observed result.

**Expected result or behaviour:**
What do you expect to happen?

/home/worker/sgf/iceoryx/iceoryx_utils/source/posix_wrapper/shared_memory_object/shared_memory.cpp:149 { bool iox::posix::SharedMemory::open(int, mode_t, uint64_t) }  :::  [ 2 ]  No such file or directory
/home/worker/sgf/iceoryx/iceoryx_utils/source/posix_wrapper/shared_memory_object/shared_memory.cpp:149 { bool iox::posix::SharedMemory::open(int, mode_t, uint64_t) }  :::  [ 2 ]  No such file or directory
Shared Memory does not exist.
Unable to create shared memory with the following properties [ name = /iceoryx_mgmt, access mode = AccessMode::READ_WRITE, ownership = OwnerShip::OPEN_EXISTING, mode = 0000, sizeInBytes = 59111944 ]
Unable to create SharedMemoryObject since we could not acquire a SharedMemory resource
Unable to create a shared memory object with the following properties [ name = /iceoryx_mgmt, sizeInBytes = 59111944, access mode = AccessMode::READ_WRITE, ownership = OwnerShip::OPEN_EXISTING, baseAddressHint = 0, permissions = 0000 ]
[0;90m2022-10-27 10:43:29.818 [0;1;31;103m[ Error ][m: ICEORYX error! POSH__SHM_APP_MAPP_ERR

**Comment by elfenpiff** [comment] 2022-10-27 09:31
@sgf201 Thanks for the report. The bug looks like the issue you already reported here: #1761 and I think they may have the same origin.

From the first look it seems that `iox-roudi` was started and then something deleted the shared memory resource `/dev/shm/iceoryx_mgmt` which we require for the zero copy inter process communication. Is it possible that you call `ipcrm -all` after `iox-roudi` was started?

**Comment by mossmaurice** [comment] 2022-12-14 18:46
@sgf201 Closing this as duplicate of #1761. Feel free to re-open if the issue persists.

**Closed by mossmaurice** 2022-12-14 18:46 UTC
Labels: duplicate
