### ISSUE TITLE
subscriber cannot get data that was sent before it started

### ISSUE THREAD

**Issue by bopeng-saitama** [eclipse-iceoryx/iceoryx#1923] opened 2023-02-26 14:34 UTC
## Required information

**Operating system:**
Ubuntu 22.04.1 LTS

**Compiler version:**
GCC 11.3.0

**Eclipse iceoryx version:**
v2.0.3

**Observed result or behaviour:**
When data is sent only once and before the subscriber start, the subscriber cannot get the data by Listener approach. 
Related to https://github.com/ros2/rmw_cyclonedds/issues/401.

**Expected result or behaviour:**
When data is sent before the subscriber, the subscriber can receive the data.

**Conditions where it occurred / Performed steps:**
This issue can be reproduced using callback_in_c in the iceoryx_example.
_reproduce step:_

- Reduce the frequency of publishing in ice_c_callbacks_publisher.c

    ` sleep_for(10000);`

- Start in the following order

```
#Terminal 1
./install/iceoryx_posh/bin/iox-roudi

#Terminal 2
./install/example_callbacks_in_c/bin/iox-c-callbacks-publisher

#Terminal 3
./install/example_callbacks_in_c/bin/iox-c-callbacks-with-context-data
```
![Screenshot from 2023-02-26 23-20-55](https://user-images.githubusercontent.com/82485734/221416287-e9d72ca4-0059-4cc7-8cfc-ca5659e75b5b.png)

It can be seen from the diagram that the publisher sent 0 before the subscriber started, but the subscriber did not receive 0 after it started.

![Screenshot from 2023-02-26 23-21-03](https://user-images.githubusercontent.com/82485734/221416312-f07bfe3c-59e3-4b3a-a080-dbe625c15980.png)

And after the publisher sends new data, the subscriber can receive that data normally.

**Comment by bopeng-saitama** [comment] 2023-02-27 10:40
@elfenpiff 
Thanks for the reply. 
But if cyclonedds use the current design of the Listener, wouldn`t the  transient_local policy cannot be work when we enable the shared memory?

cyclonedds/src/core/ddsc/src/shm_monitor.c
```
dds_return_t shm_monitor_attach_reader(shm_monitor_t* monitor, struct dds_reader* reader) 
{

    if(iox_listener_attach_subscriber_event_with_context_data(monitor->m_listener,
                                                              reader->m_iox_sub,
                                                              SubscriberEvent_DATA_RECEIVED,
                                                              shm_subscriber_callback,
                                                              &reader->m_iox_sub_context) != ListenerResult_SUCCESS) {
        DDS_CLOG(DDS_LC_SHM, &reader->m_rd->e.gv->logconfig, "error attaching reader\n");    
        return DDS_RETCODE_OUT_OF_RESOURCES;
    }
    ++monitor->m_number_of_attached_readers;
    return DDS_RETCODE_OK;
}
```

**Comment by elfenpiff** [comment] 2023-02-27 13:03
@bopeng-saitama Then it seems to be a bug in cyclone dds. Could you please create an issue there so that it can be addressed. 

cc @MatthiasKillat since you know the cyclone dds code best.

**Comment by bopeng-saitama** [comment] 2023-02-27 14:49
> Then it seems to be a bug in cyclone dds. Could you please create an issue there so that it can be addressed.

Sure, wiil do.

**Comment by MatthiasKillat** [comment] 2023-03-13 07:36
@elfenpiff @bopeng-saitama The intention in CycloneDDS with transient local and shared memory enabled is that with transient local the data is buffered somehow at the publisher. Either in an iceoryx buffer or in the CycloneDDS writer caches itself. The latter case must happen anyway to support hypothetical network subscribers (so efficiency is lost regardless).

I do not remember the details, but I am fairly sure it operates under the assumption that the iceoryx listener has to behave as you describe, that is be notify subscribers if there is data in some queue(s) that it observes.

This includes waking subscribers hat join after the data is put into the writer cache. Otherwise I consider this behavior of the listener incorrect. In essence, it is (or should be ) a beefed up condition variable with an extra background thread that checks waits for notification. It should behave just like a combination of a thread, a queue and a thread that waits for the queue not being empty. The thread would sleep while there is no data, but when data arrives frequently there will be many context switches with extra care being taken (which would be busy waiting).

So I am not so sure yet whether CycloneDDS is broken or the listener is not working as expected.

 @elfenpiff

**Comment by elfenpiff** [comment] 2023-03-13 11:24
@MatthiasKillat @eboasson @bopeng-saitama 

Please see this here: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/design/listener.md , the first two paragraphs.

```
Whenever the object receives the specified event the corresponding callback is called 
in the Listener background thread as a reaction.

The two key differences to the WaitSet are that the Listener is event-driven and not 
event- and state-driven as the WaitSet ...
```

> So I am not so sure yet whether CycloneDDS is broken or the iceoryx listener is not working as expected.

The Listener is in this case working as expected. If an event of an object is received before it was attached to the Listener we are unable to trigger the condition variable since it is not yet known.

The purpose of the Listener is to react on events of attached objects while they are being attached. If an event occurs before the object is attached or after it was detached the Listener will not react.

If one has this use case one can approach it by either using the Waitset in a separate thread or by attaching an additional user trigger which is triggered manually after a new object was attached.

**Comment by elBoberido** [comment] 2024-02-04 21:09
@bopeng-saitama closing this issue since the iceoryx listener works as intended and the issue lies in the upper framework

**Closed by elBoberido** 2024-02-04 21:09 UTC
Labels: question
