### ISSUE TITLE
When cyclonedds-cxx uses iox-roudi to implement shm communication, data will be lost

### ISSUE THREAD

**Issue by YeahhhhLi** [eclipse-iceoryx/iceoryx#1868] opened 2023-02-03 08:17 UTC
## Required information

**Operating system:**
Ubuntu 20.94

**Compiler version:**
GCC 9.4.0

**Soft vesion:**
cyclonedds-cxx : 0.10
cyclonedds: 0.10
iceoryx: 2.0.2

When we use cyclonedds interprocess communication, the iox-roudi service is used. But found a problem, here is a detailed description: 
When we use cyclonedds interprocess communication, the iox-roudi service is used. But found a very strange phenomenon
https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/365

As a comparison, we canceled the shm communication mode and switched to udp, and found that all data can be received

During the whole process, the iox-roudi service has no relevant logs.

**Comment by elfenpiff** [comment] 2023-02-03 09:54
@YeahhhhLi I would not exclude that this bug is originating in iceoryx but I would await here the analysis of cyclone-dds.

From our perspective cyclone-dds is a thirdparty library which has nothing to do with iceoryx. They just use it as a library. This means we have no knowledge of how, where and when it is being used in their code-base and therefore cannot analyse a bug in this context.

If you could provide some reproducible steps how to trigger this issue in iceoryx directly we can start working on this issue.

**Comment by YeahhhhLi** [comment] 2023-02-03 10:49
> This means we have no knowledge of how, where and when it is being used in their code-base and therefore cannot analyse a bug in this context.

Yes, we are directly using cyclonedds, but when troubleshooting the problem, we found that when using iox-roudi communication and directly using udp communication, the result of the subscriber receiving the message is different.

> If you could provide some reproducible steps how to trigger this issue in iceoryx directly we can start working on this issue.

In fact, I don't know how to directly use iceoryx to reproduce the problem, but I can try to simplify the use of cyclonedds as much as possible to reproduce

In addition, I would like to ask, is there a way to see more log information of iox-roudi?
Currently I can only see the following logs
```bash
iox-roudi -c iox_config.toml
```
```text
Log level set to: [Warning]
Reserving 66112408 bytes in the shared memory [iceoryx_mgmt]
[ Reserving shared memory successful ] 
Reserving 7903232000 bytes in the shared memory [domain_users]
[ Reserving shared memory successful ] 
RouDi is ready for clients
```

**Comment by elfenpiff** [comment] 2023-02-03 12:34
@YeahhhhLi I suspect a bug in cyclone-dds. The communication you described is very well tested on iceoryx side (which does not make a bug impossible). It has to be fixed in cyclone-dds side first and when in the process of fixing it a iceoryx problem is discovered we can continue here.

**Comment by dkroenke** [comment] 2023-02-03 12:49
@YeahhhhLi You can set the log level for with the `-l` option.
Example: `iox-roudi -c iox_config.toml -l debug`

See `iox-roudi --help` for more information.

**Comment by YeahhhhLi** [comment] 2023-02-07 03:38
> @YeahhhhLi You can set the log level for with the `-l` option. Example: `iox-roudi -c iox_config.toml -l debug`
> 
> See `iox-roudi --help` for more information.

Thanks~

**Comment by YeahhhhLi** [comment] 2023-02-07 03:40
> @YeahhhhLi I suspect a bug in cyclone-dds. The communication you described is very well tested on iceoryx side (which does not make a bug impossible). It has to be fixed in cyclone-dds side first and when in the process of fixing it a iceoryx problem is discovered we can continue here.



> @YeahhhhLi depending on how Cyclone DDS uses iceoryx it might indeed look like data will be lost. By default iceoryx uses a so called safe-overflowing queue of fixed size. This means that a slow consumer does not affect a fast producer but once the queue is full, the producer will remove the oldest data from the queue in order to add the new data. In theory Cyclone DDS should only use iceoryx when the QoS do not clash with this behavior. There is also an alternate behavior which lets the producer wait when the consumer is too slow but I'm not sure if Cyclone DDS uses this feature for specific QoS settings.
> 
> cc @dkroenke @elfenpiff

If there is a fixed-length queue, it may indeed cause our current problem. What is the default length of this queue? Is it topic granular? Or if there is any relevant information, I can also look at it.  Thanks!

**Comment by elBoberido** [comment] 2023-04-06 12:52
@YeahhhhLi can this issue be closed? It seems it is either a Cyclone DDS issue or just a matter of using the right QOS.

**Comment by elBoberido** [comment] 2024-02-04 21:10
@YeahhhhLi closing this issue since it seems to be a problem in an upper layer.

**Closed by elBoberido** 2024-02-04 21:10 UTC
Labels: question
