### ISSUE TITLE
TranslateAndCallTypelessCallback  Segmentation fault

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx#2163] opened 2024-01-18 09:23 UTC
## Required information

**Operating system:**
Ubuntu 20.04 LTS

**Compiler version:**
E.g. GCC9.5.0

**Eclipse iceoryx version:**
`v2.0.3`

**Observed result or behaviour:**
Loop running test cases，this fault has a very low probability of occurring

**Expected result or behaviour:**
work

**Conditions where it occurred / Performed steps:**
looping steps below
ros2 run decode.py

Describe how one can reproduce the bug.
[decodec-15] Stack trace (most recent call last) in thread 2915696:
[decodec-15] #7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in
[decodec-15] #6    Object "/lib/aarch64-linux-gnu/libc.so.6", at 0xffffbe26762b, in
[decodec-15] #5    Object "/lib/aarch64-linux-gnu/libpthread.so.0", at 0xffffbe16c623, in
[decodec-15] #4    Object "/lib/aarch64-linux-gnu/libstdc++.so.6", at 0xffffbe3f9f9b, in 
[decodec-15] #3    Object "/opt/nros/lib/libiceoryx_posh.so", at 0xffffbd672dc3, in iox::popo::ListenerImpl<256ul>::threadLoop()
[decodec-15] #2    Object "/opt/nros/lib/libiceoryx_posh.so", at 0xffffbd672bd3, in iox::popo::internal::Event_t::executeCallback()
[decodec-15] #1    Object "/opt/nros/lib/libiceoryx_binding_c.so", at 0xffffbd9cc8e3, in iox::popo::internal::TranslateAndCallTypelessCallback<cpp2c_Subscriber, void>::call(void*, void*, void (*)())
[decodec-15] #0    Object "/opt/nros/lib/libddsc.so.0", at 0xffffbdbba4a4, in
[decodec-15] Segmentation fault (Address not mapped to object [0x44])

**Comment by elBoberido** [comment] 2024-01-19 16:44
@sgf201 can you create a small example without the ROS/DDS layer and only the iceoryx API?

**Comment by sgf201** [comment] 2024-01-27 14:25
> @sgf201 can you create a small example without the ROS/DDS layer and only the iceoryx API?
@elBoberido 
Sorry, I can't reproduce this issue in pure iceoryx, and I'm not even familiar with using only iceoryx to implement this feature. This cannot be considered a bug submission. I really want to ask what may have caused this phenomenon. I will pay attention to and troubleshoot it later



There is additional information that this issue occurred when I simultaneously started multiple ROS2 nodes under root, and both roudi and app were started with root privileges. This issue has never occurred when starting with a user

**Comment by elBoberido** [comment] 2024-01-27 15:47
@sgf201 after a closer look, it seems the crash happens in libddsc.so. A wild guess would be that either the callback is invalidated but not yet removed from the listener or the callback does something fishy. I would suggest to build the dds layer with debug symbols to get more meaningful information.

I'm closing the issue since it seems highly unlikely to have the root cause in iceoryx itself. Fell free to re-open it if you get more information that points towards iceoryx.

**Closed by elBoberido** 2024-01-27 15:47 UTC
Labels: question
