### ISSUE TITLE
take() fail when subscriber.hasData() returns true 

### ISSUE THREAD

**Issue by ChYUYAO** [eclipse-iceoryx/iceoryx#2048] opened 2023-10-20 03:42 UTC
## Required information

**Operating system:**
E.g. Ubuntu 20.04 LTS

**Observed result or behaviour:**
the subscriber can take msg for about 10min than can not take msg forever
![image](https://github.com/eclipse-iceoryx/iceoryx/assets/52686540/fb621f69-104f-4c00-939e-af982bd3636b)

**Expected result or behaviour:**
will not print "Error receiving chunk".

**Conditions where it occurred / Performed steps:**
code format is liking this below.
```
  while (true) {
    if (subscriber.hasData()) {
      subscriber_.get()
          ->take()
          .and_then([&](const void *userPayload) {})
          .or_else([](auto &result) {
            if (result != iox::popo::ChunkReceiveResult::NO_CHUNK_AVAILABLE) {
              std::cout << "Error receiving chunk." << std::endl;
            }
          });
    }
  }
```
I wonder know when this will happen?

**Comment by elBoberido** [comment] 2023-10-20 11:00
@ChYUYAO Do you access the subscriber from multiple threads?

**Comment by ChYUYAO** [comment] 2023-10-20 11:12
> @ChYUYAO Do you access the subscriber from multiple threads?

No,There is only one threads and one subscriber in th process.But there are multiple processors have subscribed the same topic.

**Comment by ChYUYAO** [comment] 2023-10-20 11:18
However, the data I take will not release() in time, and sometimes release() will be made after I get several data

**Comment by elBoberido** [comment] 2023-10-20 11:55
Can you print the error code? A simple `std::cout << "Error receiving chunk: " << result << std::endl;` should work.

**Comment by ChYUYAO** [comment] 2023-10-23 02:55
> Can you print the error code? A simple `std::cout << "Error receiving chunk: " << result << std::endl;` should work.
> 
> Although, looking at the enum, the only other option is `TOO_MANY_CHUNKS_HELD_IN_PARALLEL`. This means you are holding too many chunks and need to release them before you are able to take more.

how many  chunks I can hold?If result != iox::popo::ChunkReceiveResult::NO_CHUNK_AVAILABLE , then result only will be TOO_MANY_CHUNKS_HELD_IN_PARALLEL?

**Comment by ChYUYAO** [comment] 2023-10-23 03:02
> Can you print the error code? A simple `std::cout << "Error receiving chunk: " << result << std::endl;` should work.
> 
> Although, looking at the enum, the only other option is `TOO_MANY_CHUNKS_HELD_IN_PARALLEL`. This means you are holding too many chunks and need to release them before you are able to take more.

I have see the chunks I can hold is 256?It is unlikely that the chunks held by my program will exceed this value. If result != iox::popo::ChunkReceiveResult::NO_CHUNK_AVAILABLE , then result only will be TOO_MANY_CHUNKS_HELD_IN_PARALLEL?

**Comment by elBoberido** [comment] 2023-10-23 13:52
You can configure the size by `-DIOX_MAX_CHUNKS_HELD_PER_SUBSCRIBER_SIMULTANEOUSLY=512` cmake option.

Closing the issue since the code works as intended

**Closed by elBoberido** 2023-10-23 13:52 UTC

**Comment by ChYUYAO** [comment] 2024-04-30 03:41
> Can you print the error code? A simple `std::cout << "Error receiving chunk: " << result << std::endl;` should work.
> 
> Although, looking at the enum, the only other option is `TOO_MANY_CHUNKS_HELD_IN_PARALLEL`. This means you are holding too many chunks and need to release them before you are able to take more.

Hello,I have tried this and the opions is iox::popo::ChunkReceiveResult::NO_CHUNK_AVAILABLE.When will this happend.

**Comment by elBoberido** [comment] 2024-04-30 10:21
Can you provide a minimal example with a publisher and subscriber which triggers the issue?
