### ISSUE TITLE
why iceoryx didn't use robust mutex for roudi deadlock?

### ISSUE THREAD

**Issue by qclzdh** [eclipse-iceoryx/iceoryx#1042] opened 2022-01-25 08:36 UTC
https://github.com/eclipse-iceoryx/iceoryx/blob/771ad556d443f963318181d3cd9598f7388bf66a/iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl#L334

why iceoryx didn't use robust mutex for roudi deadlock?

pthread_mutexattr_setrobust was introduced here:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutexattr_setrobust.html

**Comment by elfenpiff** [comment] 2022-01-25 10:25
@qclzdh Actually this wouldn't be the solution here. Yes we could use the robust mutex feature and maybe we introduce it into our `posix::mutex` abstraction. The problem is that one has to identify a deadlock, in our case this is discovered via missing heartbeats over the last 2 seconds. If this is the case we could solve the deadlock here. But a lot can happen in 2 seconds - especially in a safety critical environment. And what happens when we made a mistake and the deadlock we identified is actually not a deadlock?

Therefore, we are working on a lock-free solution with atomics which will remove the deadlock issue once and for all.

In the past we solved all deadlock issues with our lockfree queue and other lock free construct and this is the only remaining piece.

**Comment by elBoberido** [comment] 2022-01-25 10:57
@qclzdh furthermore, we must also ensure that the data which is guarded by the mutex is not corrupt or at least can be recovered

**Comment by qclzdh** [comment] 2022-01-26 01:34
@elfenpiff @elBoberido  Thanks for clarification, yes, a lock-free solution would be better,  Does 2.0 release include this?

BTW, can 2.0-release  achieve some ASIL-D or ASIL-B?

**Comment by mossmaurice** [comment] 2022-01-26 09:47
> BTW, can 2.0-release achieve ASIL-D or ASIL-B?

Although, iceoryx is used in commercial products like [Apex.Middlware](https://www.apex.ai/apex-middleware), [RTA-VRTE](https://www.etas.com/en/products/rta-vrte.php) or [Avin AP](https://www.avinsystems.com/products/autosar_ap_solutions/) which will eventually get an ISO26262 ASIL certification, it probably won't receive a ASIL standalone. The code alone is not enough when it comes to ISO26262, but you need things like requirements, MC/DC tests and safety concept & manual. You can learn more about the iceoryx approach in [my talk](https://www.youtube.com/watch?v=e20Y2yeiD1M) on last years EclipseCon. Feel free to drop me a line if you have further questions.

**Comment by elfenpiff** [comment] 2022-01-26 09:48
@qclzdh Release 2.0 will not yet include this feature but we intend to implement a solution this year.

**Comment by elfenpiff** [comment] 2022-01-26 09:53
@mossmaurice Maybe we should add this to the documentation how one could acquire an ASIL-D certified iceoryx and how the time schedule roughly looks like on our side. Maybe also with a first idea what kind of features an ASIL-D iceoryx will support and what features will be definitely excluded.

@qclzdh I think that the API of a certified ASIL-D iceoryx will be very similar to the 2.0 version and in the worst case you only have minor changes. But it is very likely that an ASIL-D version of iceoryx will not have the same feature set. We have to work on a document to make this visible for all the iceoryx users so that all developers can plan their projects accordingly.

**Comment by mossmaurice** [comment] 2022-04-27 14:45
Duplicate of #325, closing this issue. @qclzdh Feel free to reopen if you have more questions.

**Closed by mossmaurice** 2022-04-27 14:45 UTC
Labels: question

**Comment by qclzdh** [comment] 2022-10-12 05:19
> > BTW, can 2.0-release achieve ASIL-D or ASIL-B?
> 
> Although, iceoryx is used in commercial products like [Apex.Middlware](https://www.apex.ai/apex-middleware), [RTA-VRTE](https://www.etas.com/en/products/rta-vrte.php) or [Avin AP](https://www.avinsystems.com/products/autosar_ap_solutions/) which will eventually get an ISO26262 ASIL certification, it probably won't receive an ASIL standalone. The code alone is not enough when it comes to ISO26262, but you need things like requirements, MC/DC tests and safety concept & manual. You can learn more about the iceoryx approach in [my talk](https://www.youtube.com/watch?v=e20Y2yeiD1M) on last years EclipseCon. Feel free to drop me a line if you have further questions.

@elfenpiff @mossmaurice 
could you leave me one e-mail address for further communication about the funcational safe ISO26262 version?

**Comment by mossmaurice** [comment] 2022-10-12 12:42
@qclzdh For questions on products offered by Apex.AI please write an email to products@apex.ai thanks!
