### ISSUE TITLE
Building blocks in iceoryx

### ISSUE THREAD

**Issue by dkroenke** [eclipse-iceoryx/iceoryx#252] opened 2020-08-19 07:38 UTC
Brief feature description

For a better modularization and customization of the iceoryx ports, we need to have building blocks where the customer can build the ports with his own flavor. For example we want to make the queue in the receiver port portable so that the customer can either have a Sofi or a MPMC queue in it.

We want to do the following points:

- [x] 1: Implement NewType Pattern for UniqueID 
- [x] 2: use UniqueID implementation in building Blocks 
- [x] 3: C Language binding
- [x] 4: Modern C++ API implementation
- [x] 5: runnable abstraction #349
- [x] 6: Modern C++ API proposal - cxx::unique_ptr 
- [x] 7: Modern C++ API proposal - Typed Publisher 
- [x] 8: Modern C++ API proposal - Typed Subscriber 
- [x] 9: Replacement of old ports in iceoryx with new building block ones
- [x] 10: Modern C++ API Proposal - Untyped
- [x] 11: Top layer integration tests #378 
- [x] 12: API documentation #283 
- [x] 13: callbacks in the new APIs #350

**Comment by dkroenke** [comment] 2020-08-19 07:39
@budrus Maybe you want to add something if you want.

**Comment by mossmaurice** [comment] 2020-08-19 09:38
This is a duplicate of #25?

**Comment by dkroenke** [comment] 2020-08-19 09:51
@mossmaurice whats is duplicated?

**Comment by mossmaurice** [comment] 2020-11-11 13:01
Reopening as @marthtz and myself are still working on this.

**Closed** 2021-03-21 10:02 UTC
Labels: enhancement, refactoring
